const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const empresas = await prisma.empresa.findMany();
  const eventos = await prisma.evento.findMany();

  const em = {};
  for (const e of empresas) em[e.nombre] = e.id;

  const ev = {};
  for (const e of eventos) ev[e.nombre] = e.id;

  const productos = [
    // Samsung Chile (10)
    { empresaId: em['Samsung Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Samsung Galaxy S24 Ultra 256GB', descripcion: 'Smartphone insignia con S Pen, cámara 200MP y Snapdragon 8 Gen 3.', categoria: 'Electrónica', precioOriginal: 999990, precioEvento: 649990, descuento: 35, stock: 25, stockMinimo: 3, sku: 'SAM-S24U-001', condicion: 'nuevo', tags: ['smartphone'], visitas: 5800 },
    { empresaId: em['Samsung Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Smart TV Samsung 65" Neo QLED 4K', descripcion: 'Televisor Neo QLED con Mini LED y HDR10+.', categoria: 'Electrónica', precioOriginal: 1299990, precioEvento: 779990, descuento: 40, stock: 30, stockMinimo: 3, sku: 'SAM-TV65-002', condicion: 'nuevo', tags: ['televisor'], visitas: 4200 },
    { empresaId: em['Samsung Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Samsung Galaxy Tab S9 FE', descripcion: 'Tablet 10.9" con Exynos 1380 y S Pen incluido.', categoria: 'Electrónica', precioOriginal: 499990, precioEvento: 299990, descuento: 40, stock: 40, stockMinimo: 5, sku: 'SAM-TAB-003', condicion: 'nuevo', tags: ['tablet'], visitas: 3100 },
    { empresaId: em['Samsung Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Samsung Soundbar HW-Q990C', descripcion: 'Barra de sonido 11.1.4ch con Dolby Atmos.', categoria: 'Electrónica', precioOriginal: 799990, precioEvento: 479990, descuento: 40, stock: 15, stockMinimo: 2, sku: 'SAM-SB-004', condicion: 'nuevo', tags: ['audio'], visitas: 2100 },
    { empresaId: em['Samsung Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Monitor Samsung Odyssey G7 27"', descripcion: 'Monitor gaming curvo QLED 2K 240Hz.', categoria: 'Electrónica', precioOriginal: 599990, precioEvento: 369990, descuento: 38, stock: 20, stockMinimo: 3, sku: 'SAM-MON-005', condicion: 'nuevo', tags: ['monitor'], visitas: 2800 },
    { empresaId: em['Samsung Chile'], eventoId: ev['Samsung Back to School'], nombre: 'Samsung Galaxy Book3 Pro 14"', descripcion: 'Notebook con Intel Core i7, 16GB RAM y pantalla AMOLED.', categoria: 'Electrónica', precioOriginal: 1199990, precioEvento: 799990, descuento: 33, stock: 18, stockMinimo: 2, sku: 'SAM-NB-006', condicion: 'nuevo', tags: ['notebook'], visitas: 3900 },
    { empresaId: em['Samsung Chile'], eventoId: ev['Samsung Back to School'], nombre: 'Samsung Galaxy Watch 6 Classic', descripcion: 'Smartwatch con bisel giratorio, ECG y GPS.', categoria: 'Electrónica', precioOriginal: 299990, precioEvento: 199990, descuento: 33, stock: 35, stockMinimo: 5, sku: 'SAM-WCH-007', condicion: 'nuevo', tags: ['smartwatch'], visitas: 2400 },
    { empresaId: em['Samsung Chile'], eventoId: ev['Samsung Back to School'], nombre: 'Samsung Galaxy Buds2 Pro', descripcion: 'Audífonos inalámbricos con ANC y Hi-Fi 24bit.', categoria: 'Electrónica', precioOriginal: 149990, precioEvento: 89990, descuento: 40, stock: 50, stockMinimo: 8, sku: 'SAM-BUD-008', condicion: 'nuevo', tags: ['audífonos'], visitas: 3200 },
    { empresaId: em['Samsung Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Samsung Refrigerador French Door 640L', descripcion: 'Refrigerador con Family Hub y All-Around Cooling.', categoria: 'Hogar', precioOriginal: 1499990, precioEvento: 999990, descuento: 33, stock: 8, stockMinimo: 1, sku: 'SAM-REF-009', condicion: 'nuevo', tags: ['refrigerador'], visitas: 1800 },
    { empresaId: em['Samsung Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Samsung Microondas Smart 32L', descripcion: 'Microondas con sensor de cocción y control por voz.', categoria: 'Hogar', precioOriginal: 199990, precioEvento: 129990, descuento: 35, stock: 22, stockMinimo: 3, sku: 'SAM-MIC-010', condicion: 'nuevo', tags: ['microondas'], visitas: 1200 },

    // Falabella (10)
    { empresaId: em['Falabella'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Chaqueta North Face Thermoball', descripcion: 'Chaqueta acolchada con relleno Thermoball para temperaturas bajo cero.', categoria: 'Moda', precioOriginal: 149990, precioEvento: 74990, descuento: 50, stock: 60, stockMinimo: 10, sku: 'FAL-NF-001', condicion: 'nuevo', tags: ['outdoor'], visitas: 4100 },
    { empresaId: em['Falabella'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Robot Aspirador Roomba i7+', descripcion: 'Aspirador robot con vaciado automático y navegación inteligente.', categoria: 'Hogar', precioOriginal: 499990, precioEvento: 299990, descuento: 40, stock: 18, stockMinimo: 2, sku: 'FAL-ROOM-002', condicion: 'nuevo', tags: ['robot'], visitas: 5200 },
    { empresaId: em['Falabella'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Cafetera Nespresso Vertuo Next', descripcion: 'Cafetera de cápsulas con tecnología Centrifusion.', categoria: 'Hogar', precioOriginal: 89990, precioEvento: 49990, descuento: 44, stock: 85, stockMinimo: 10, sku: 'FAL-NESP-003', condicion: 'nuevo', tags: ['café'], visitas: 6800 },
    { empresaId: em['Falabella'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Zapatillas Nike Air Max 270', descripcion: 'Zapatillas lifestyle con cámara de aire 270°.', categoria: 'Moda', precioOriginal: 99990, precioEvento: 59990, descuento: 40, stock: 120, stockMinimo: 15, sku: 'FAL-NIK-004', condicion: 'nuevo', tags: ['zapatillas'], visitas: 7200 },
    { empresaId: em['Falabella'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Juego de Living 3 Piezas Premium', descripcion: 'Sofá 3 cuerpos + 2 sillones tapizados en tela antimanchas.', categoria: 'Hogar', precioOriginal: 599990, precioEvento: 349990, descuento: 42, stock: 12, stockMinimo: 2, sku: 'FAL-LIV-005', condicion: 'nuevo', tags: ['muebles'], visitas: 3400 },
    { empresaId: em['Falabella'], eventoId: ev['Falabella Invierno Flash'], nombre: 'Parka Columbia Impermeable', descripcion: 'Parka certificada para -20°C con tecnología Omni-Tech.', categoria: 'Moda', precioOriginal: 129990, precioEvento: 64990, descuento: 50, stock: 45, stockMinimo: 8, sku: 'FAL-COL-006', condicion: 'nuevo', tags: ['parka'], visitas: 3800 },
    { empresaId: em['Falabella'], eventoId: ev['Falabella Invierno Flash'], nombre: 'Set Ropa Interior Térmica', descripcion: 'Polera y pantalón térmico para temperaturas extremas.', categoria: 'Moda', precioOriginal: 39990, precioEvento: 19990, descuento: 50, stock: 200, stockMinimo: 20, sku: 'FAL-TER-007', condicion: 'nuevo', tags: ['térmica'], visitas: 2100 },
    { empresaId: em['Falabella'], eventoId: ev['Falabella Invierno Flash'], nombre: 'Manta Eléctrica Peabody 180x150cm', descripcion: 'Manta eléctrica con 3 niveles de temperatura y apagado automático.', categoria: 'Hogar', precioOriginal: 49990, precioEvento: 29990, descuento: 40, stock: 80, stockMinimo: 10, sku: 'FAL-MAN-008', condicion: 'nuevo', tags: ['hogar'], visitas: 4200 },
    { empresaId: em['Falabella'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Silla Gamer DXRacer Formula', descripcion: 'Silla gaming ergonómica con soporte lumbar ajustable.', categoria: 'Hogar', precioOriginal: 249990, precioEvento: 149990, descuento: 40, stock: 25, stockMinimo: 3, sku: 'FAL-DXR-009', condicion: 'nuevo', tags: ['gaming'], visitas: 3600 },
    { empresaId: em['Falabella'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Licuadora Ninja Professional 1500W', descripcion: 'Licuadora profesional con vaso 2.1L y cuchillas de acero inoxidable.', categoria: 'Hogar', precioOriginal: 79990, precioEvento: 44990, descuento: 44, stock: 55, stockMinimo: 8, sku: 'FAL-NIN-010', condicion: 'nuevo', tags: ['cocina'], visitas: 2900 },

    // Cencosud (10)
    { empresaId: em['Cencosud'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Pack Vinos Santa Rita Medalla Real 6u', descripcion: 'Selección premium de 6 vinos incluyendo Cabernet, Carménère y Chardonnay.', categoria: 'Alimentos', precioOriginal: 89990, precioEvento: 59990, descuento: 33, stock: 200, stockMinimo: 20, sku: 'CEN-VIN-001', condicion: 'nuevo', tags: ['vinos'], visitas: 1200 },
    { empresaId: em['Cencosud'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Parrilla Weber Master-Touch 57cm', descripcion: 'Parrilla a carbón premium con tapa y sistema de ventilación.', categoria: 'Hogar', precioOriginal: 249990, precioEvento: 164990, descuento: 34, stock: 35, stockMinimo: 5, sku: 'CEN-WEB-002', condicion: 'nuevo', tags: ['parrilla'], visitas: 890 },
    { empresaId: em['Cencosud'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Set Cuchillos Wüsthof Classic 7 piezas', descripcion: 'Set de cuchillos profesionales alemanes con bloque de madera.', categoria: 'Hogar', precioOriginal: 199990, precioEvento: 129990, descuento: 35, stock: 40, stockMinimo: 5, sku: 'CEN-WUS-003', condicion: 'nuevo', tags: ['cuchillos'], visitas: 1500 },
    { empresaId: em['Cencosud'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Jamón Serrano Reserva 1kg', descripcion: 'Jamón serrano curado 18 meses, importado desde España.', categoria: 'Alimentos', precioOriginal: 49990, precioEvento: 32990, descuento: 34, stock: 150, stockMinimo: 20, sku: 'CEN-JAM-004', condicion: 'nuevo', tags: ['jamón'], visitas: 980 },
    { empresaId: em['Cencosud'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Pack Quesos Premium Europeos 4u', descripcion: 'Brie, Gouda añejo, Manchego y Parmesano importados.', categoria: 'Alimentos', precioOriginal: 35990, precioEvento: 24990, descuento: 31, stock: 180, stockMinimo: 20, sku: 'CEN-QUE-005', condicion: 'nuevo', tags: ['quesos'], visitas: 760 },
    { empresaId: em['Cencosud'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Whisky Johnnie Walker Black Label 750ml', descripcion: 'Blend premium escocés envejecido 12 años.', categoria: 'Alimentos', precioOriginal: 39990, precioEvento: 27990, descuento: 30, stock: 120, stockMinimo: 15, sku: 'CEN-WHI-006', condicion: 'nuevo', tags: ['whisky'], visitas: 2100 },
    { empresaId: em['Cencosud'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Aceite de Oliva Extra Virgen 5L', descripcion: 'Aceite premium de primera prensada en frío.', categoria: 'Alimentos', precioOriginal: 29990, precioEvento: 19990, descuento: 33, stock: 250, stockMinimo: 30, sku: 'CEN-ACE-007', condicion: 'nuevo', tags: ['aceite'], visitas: 640 },
    { empresaId: em['Cencosud'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Champagne Moët & Chandon Brut 750ml', descripcion: 'Champagne francés con notas de manzana y pera.', categoria: 'Alimentos', precioOriginal: 59990, precioEvento: 42990, descuento: 28, stock: 80, stockMinimo: 10, sku: 'CEN-CHA-008', condicion: 'nuevo', tags: ['champagne'], visitas: 1800 },
    { empresaId: em['Cencosud'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Café Especialidad Ethiopia 500g', descripcion: 'Café de origen único tostado artesanal con notas florales.', categoria: 'Alimentos', precioOriginal: 24990, precioEvento: 16990, descuento: 32, stock: 300, stockMinimo: 30, sku: 'CEN-CAF-009', condicion: 'nuevo', tags: ['café'], visitas: 920 },
    { empresaId: em['Cencosud'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Salmón Premium Fresco 1kg', descripcion: 'Salmón fresco de cultivo sustentable listo para cocinar.', categoria: 'Alimentos', precioOriginal: 19990, precioEvento: 13990, descuento: 30, stock: 500, stockMinimo: 50, sku: 'CEN-SAL-010', condicion: 'nuevo', tags: ['salmón'], visitas: 1100 },

    // Latam Airlines (10)
    { empresaId: em['Latam Airlines'], eventoId: ev['Latam Travel Benefits'], nombre: 'Upgrade Business Class Nacional', descripcion: 'Upgrade a Business en vuelos nacionales con lounge incluido.', categoria: 'Otro', precioOriginal: 149990, precioEvento: 79990, descuento: 47, stock: 200, stockMinimo: 20, sku: 'LAT-UPG-001', condicion: 'nuevo', tags: ['viaje'], visitas: 3400 },
    { empresaId: em['Latam Airlines'], eventoId: ev['Latam Travel Benefits'], nombre: 'Upgrade Business Class Internacional', descripcion: 'Upgrade internacional con asiento cama y amenity kit.', categoria: 'Otro', precioOriginal: 399990, precioEvento: 249990, descuento: 38, stock: 100, stockMinimo: 10, sku: 'LAT-INT-002', condicion: 'nuevo', tags: ['internacional'], visitas: 4200 },
    { empresaId: em['Latam Airlines'], eventoId: ev['Latam Travel Benefits'], nombre: 'Pack Equipaje Adicional 23kg', descripcion: 'Prepago de equipaje adicional para cualquier vuelo Latam.', categoria: 'Otro', precioOriginal: 49990, precioEvento: 29990, descuento: 40, stock: 500, stockMinimo: 50, sku: 'LAT-EQU-003', condicion: 'nuevo', tags: ['equipaje'], visitas: 2800 },
    { empresaId: em['Latam Airlines'], eventoId: ev['Latam Travel Benefits'], nombre: 'Acceso Sala VIP LATAM 1 día', descripcion: 'Acceso a salas VIP en cualquier aeropuerto de Chile.', categoria: 'Otro', precioOriginal: 34990, precioEvento: 19990, descuento: 43, stock: 300, stockMinimo: 30, sku: 'LAT-VIP-004', condicion: 'nuevo', tags: ['lounge'], visitas: 1900 },
    { empresaId: em['Latam Airlines'], eventoId: ev['Latam Travel Benefits'], nombre: 'Millas LATAM Pass 10.000', descripcion: '10.000 millas para canjear en vuelos y upgrades.', categoria: 'Otro', precioOriginal: 79990, precioEvento: 49990, descuento: 38, stock: 1000, stockMinimo: 100, sku: 'LAT-MIL-005', condicion: 'nuevo', tags: ['millas'], visitas: 5600 },
    { empresaId: em['Latam Airlines'], eventoId: ev['Latam Travel Benefits'], nombre: 'Seguro de Viaje Internacional 15 días', descripcion: 'Cobertura médica, cancelación y pérdida de equipaje.', categoria: 'Otro', precioOriginal: 29990, precioEvento: 17990, descuento: 40, stock: 500, stockMinimo: 50, sku: 'LAT-SEG-006', condicion: 'nuevo', tags: ['seguro'], visitas: 1400 },
    { empresaId: em['Latam Airlines'], eventoId: ev['Latam Travel Benefits'], nombre: 'Pack Familia Santiago-Cancún', descripcion: '2 pasajes ida y vuelta Santiago-Cancún en temporada baja.', categoria: 'Otro', precioOriginal: 1299990, precioEvento: 899990, descuento: 31, stock: 50, stockMinimo: 5, sku: 'LAT-FAM-007', condicion: 'nuevo', tags: ['familia'], visitas: 8900 },
    { empresaId: em['Latam Airlines'], eventoId: ev['Latam Travel Benefits'], nombre: 'Maleta Samsonite Spinner 75cm', descripcion: 'Maleta rígida expandible con cerradura TSA y 4 ruedas 360°.', categoria: 'Otro', precioOriginal: 149990, precioEvento: 89990, descuento: 40, stock: 80, stockMinimo: 10, sku: 'LAT-MAL-008', condicion: 'nuevo', tags: ['maleta'], visitas: 3100 },
    { empresaId: em['Latam Airlines'], eventoId: ev['Latam Travel Benefits'], nombre: 'Transfer Aeropuerto Premium', descripcion: 'Transfer privado desde/hacia aeropuerto en vehículo premium.', categoria: 'Otro', precioOriginal: 49990, precioEvento: 29990, descuento: 40, stock: 200, stockMinimo: 20, sku: 'LAT-TRA-009', condicion: 'nuevo', tags: ['transfer'], visitas: 1600 },
    { empresaId: em['Latam Airlines'], eventoId: ev['Latam Travel Benefits'], nombre: 'Almohada de Viaje Tempur Premium', descripcion: 'Almohada ergonómica viscoelástica para vuelos largos.', categoria: 'Otro', precioOriginal: 39990, precioEvento: 24990, descuento: 38, stock: 150, stockMinimo: 15, sku: 'LAT-ALM-010', condicion: 'nuevo', tags: ['comodidad'], visitas: 980 },

    // Banco de Chile (10)
    { empresaId: em['Banco de Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Tarjeta Regalo Amazon $50 USD', descripcion: 'Gift card Amazon con $50 USD válida sin vencimiento.', categoria: 'Otro', precioOriginal: 49990, precioEvento: 34990, descuento: 30, stock: 300, stockMinimo: 30, sku: 'BCH-AMZ-001', condicion: 'nuevo', tags: ['gift card'], visitas: 4500 },
    { empresaId: em['Banco de Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Suscripción Netflix Premium 6 meses', descripcion: 'Netflix plan Premium 4 pantallas en 4K por 6 meses.', categoria: 'Otro', precioOriginal: 59940, precioEvento: 39990, descuento: 33, stock: 500, stockMinimo: 50, sku: 'BCH-NET-002', condicion: 'nuevo', tags: ['streaming'], visitas: 6200 },
    { empresaId: em['Banco de Chile'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Bicicleta Urbana Oxford 26"', descripcion: 'Bicicleta urbana 21 velocidades con frenos de disco.', categoria: 'Deportes', precioOriginal: 199990, precioEvento: 129990, descuento: 35, stock: 20, stockMinimo: 3, sku: 'BCH-BIC-003', condicion: 'nuevo', tags: ['bicicleta'], visitas: 2800 },
    { empresaId: em['Banco de Chile'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Membresía SmartFit 6 meses', descripcion: 'Acceso a todos los locales SmartFit de Chile por 6 meses.', categoria: 'Deportes', precioOriginal: 89940, precioEvento: 59990, descuento: 33, stock: 200, stockMinimo: 20, sku: 'BCH-GYM-004', condicion: 'nuevo', tags: ['gimnasio'], visitas: 5100 },
    { empresaId: em['Banco de Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Kindle Paperwhite 11° generación', descripcion: 'E-reader 6.8" con luz cálida y resistencia al agua IPX8.', categoria: 'Electrónica', precioOriginal: 129990, precioEvento: 84990, descuento: 35, stock: 45, stockMinimo: 5, sku: 'BCH-KIN-005', condicion: 'nuevo', tags: ['e-reader'], visitas: 2100 },
    { empresaId: em['Banco de Chile'], eventoId: ev['Cencosud Gourmet Week'], nombre: 'Box Desayuno Gourmet Premium', descripcion: 'Té, café, mermeladas artesanales, chocolates y frutos secos.', categoria: 'Alimentos', precioOriginal: 39990, precioEvento: 26990, descuento: 33, stock: 150, stockMinimo: 15, sku: 'BCH-DES-006', condicion: 'nuevo', tags: ['gourmet'], visitas: 1800 },
    { empresaId: em['Banco de Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Apple AirPods Pro 2° generación', descripcion: 'Audífonos con ANC, modo transparencia y audio espacial.', categoria: 'Electrónica', precioOriginal: 249990, precioEvento: 179990, descuento: 28, stock: 30, stockMinimo: 5, sku: 'BCH-APP-007', condicion: 'nuevo', tags: ['Apple'], visitas: 7800 },
    { empresaId: em['Banco de Chile'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Set Yoga Premium 5 piezas', descripcion: 'Mat, bloques, correa, bolsa y toalla antideslizante.', categoria: 'Deportes', precioOriginal: 49990, precioEvento: 31990, descuento: 36, stock: 80, stockMinimo: 10, sku: 'BCH-YOG-008', condicion: 'nuevo', tags: ['yoga'], visitas: 1600 },
    { empresaId: em['Banco de Chile'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Cargador Inalámbrico Belkin 3 en 1', descripcion: 'Carga iPhone, Apple Watch y AirPods simultáneamente.', categoria: 'Electrónica', precioOriginal: 79990, precioEvento: 49990, descuento: 38, stock: 60, stockMinimo: 8, sku: 'BCH-CAR-009', condicion: 'nuevo', tags: ['cargador'], visitas: 2900 },
    { empresaId: em['Banco de Chile'], eventoId: ev['Latam Travel Benefits'], nombre: 'Cata de Vinos Valle del Maipo para 2', descripcion: 'Tour con cata de 5 vinos premium y maridaje para 2 personas.', categoria: 'Otro', precioOriginal: 89990, precioEvento: 59990, descuento: 33, stock: 50, stockMinimo: 5, sku: 'BCH-CAT-010', condicion: 'nuevo', tags: ['experiencia'], visitas: 2400 },

    // Entel (10)
    { empresaId: em['Entel'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Router WiFi 6 TP-Link Archer AX73', descripcion: 'Router tribanda hasta 5400Mbps y cobertura 250m².', categoria: 'Electrónica', precioOriginal: 99990, precioEvento: 64990, descuento: 35, stock: 40, stockMinimo: 5, sku: 'ENT-RTR-001', condicion: 'nuevo', tags: ['router'], visitas: 3200 },
    { empresaId: em['Entel'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Smartphone Motorola Edge 40 Neo 256GB', descripcion: 'Cámara 50MP, OLED 144Hz y carga rápida 68W.', categoria: 'Electrónica', precioOriginal: 299990, precioEvento: 199990, descuento: 33, stock: 35, stockMinimo: 5, sku: 'ENT-MOT-002', condicion: 'nuevo', tags: ['smartphone'], visitas: 2800 },
    { empresaId: em['Entel'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Tablet Lenovo Tab P11 Pro 2° gen', descripcion: 'OLED 11.2", 8GB RAM y stylus incluido.', categoria: 'Electrónica', precioOriginal: 399990, precioEvento: 259990, descuento: 35, stock: 25, stockMinimo: 3, sku: 'ENT-TAB-003', condicion: 'nuevo', tags: ['tablet'], visitas: 1900 },
    { empresaId: em['Entel'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Smart Speaker Amazon Echo Show 10', descripcion: 'Altavoz con pantalla rotatoria 10.1" y Alexa integrada.', categoria: 'Electrónica', precioOriginal: 199990, precioEvento: 129990, descuento: 35, stock: 30, stockMinimo: 4, sku: 'ENT-ECH-004', condicion: 'nuevo', tags: ['smart speaker'], visitas: 2400 },
    { empresaId: em['Entel'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Disco Duro Externo Seagate 4TB', descripcion: 'Disco externo USB 3.0 portátil de 4TB.', categoria: 'Electrónica', precioOriginal: 79990, precioEvento: 49990, descuento: 38, stock: 60, stockMinimo: 8, sku: 'ENT-HDD-005', condicion: 'nuevo', tags: ['almacenamiento'], visitas: 1700 },
    { empresaId: em['Entel'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Cámara de Seguridad Ezviz 360° 4K', descripcion: 'IP exterior 4K con visión nocturna a color y detección IA.', categoria: 'Electrónica', precioOriginal: 89990, precioEvento: 59990, descuento: 33, stock: 45, stockMinimo: 6, sku: 'ENT-CAM-006', condicion: 'nuevo', tags: ['seguridad'], visitas: 2100 },
    { empresaId: em['Entel'], eventoId: ev['Falabella Moda & Hogar'], nombre: 'Impresora HP LaserJet Pro M404dn', descripcion: 'Láser monocromática con doble faz automático y WiFi.', categoria: 'Electrónica', precioOriginal: 199990, precioEvento: 129990, descuento: 35, stock: 20, stockMinimo: 3, sku: 'ENT-IMP-007', condicion: 'nuevo', tags: ['impresora'], visitas: 1500 },
    { empresaId: em['Entel'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Teclado Mecánico Logitech G Pro X', descripcion: 'Gaming con switches intercambiables y RGB.', categoria: 'Electrónica', precioOriginal: 149990, precioEvento: 94990, descuento: 37, stock: 30, stockMinimo: 4, sku: 'ENT-TEC-008', condicion: 'nuevo', tags: ['gaming'], visitas: 2800 },
    { empresaId: em['Entel'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Mouse Logitech MX Master 3S', descripcion: 'Inalámbrico ergonómico con scroll electromagnético 8000 DPI.', categoria: 'Electrónica', precioOriginal: 99990, precioEvento: 64990, descuento: 35, stock: 45, stockMinimo: 6, sku: 'ENT-MOU-009', condicion: 'nuevo', tags: ['mouse'], visitas: 3100 },
    { empresaId: em['Entel'], eventoId: ev['Samsung Tech Flash #9'], nombre: 'Webcam Logitech Brio 4K Stream', descripcion: '4K con HDR y corrección de luz automática.', categoria: 'Electrónica', precioOriginal: 149990, precioEvento: 99990, descuento: 33, stock: 35, stockMinimo: 5, sku: 'ENT-WEB-010', condicion: 'nuevo', tags: ['webcam'], visitas: 2200 },
  ];

  const result = await prisma.producto.createMany({ data: productos, skipDuplicates: true });
  console.log('Productos creados:', result.count);
  await prisma.$disconnect();
}

main().catch(e => { console.error(e); process.exit(1); });
